-- MySQL Script generated by MySQL Workbench
-- Thu May 25 10:49:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema OnlineBookstoreSystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `OnlineBookstoreSystem` ;

-- -----------------------------------------------------
-- Schema OnlineBookstoreSystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineBookstoreSystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `OnlineBookstoreSystem` ;

-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Authors` (
  `author_id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `biography` VARCHAR(100) NULL DEFAULT NULL,
  `contact_details` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Publishers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Publishers` (
  `publisher_id` INT NOT NULL,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `contact_details` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`publisher_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`BookStock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`BookStock` (
  `book_stock_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone_number` VARCHAR(45) NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`book_stock_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Books` (
  `book_id` INT NOT NULL,
  `title` VARCHAR(100) NULL DEFAULT NULL,
  `author_id` INT NULL DEFAULT NULL,
  `genre` VARCHAR(45) NULL DEFAULT NULL,
  `publication_details` VARCHAR(100) NULL DEFAULT NULL,
  `Publishers_publisher_id` INT NOT NULL,
  `BookStock_book_stock_id` INT NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `author_id_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_Books_Publishers1_idx` (`Publishers_publisher_id` ASC) VISIBLE,
  INDEX `fk_Books_BookStore1_idx` (`BookStock_book_stock_id` ASC) VISIBLE,
  CONSTRAINT `author_id`
    FOREIGN KEY (`author_id`)
    REFERENCES `OnlineBookstoreSystem`.`Authors` (`author_id`),
  CONSTRAINT `fk_Books_Publishers1`
    FOREIGN KEY (`Publishers_publisher_id`)
    REFERENCES `OnlineBookstoreSystem`.`Publishers` (`publisher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Books_BookStore1`
    FOREIGN KEY (`BookStock_book_stock_id`)
    REFERENCES `OnlineBookstoreSystem`.`BookStock` (`book_stock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Customers` (
  `customer_id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(100) NULL DEFAULT NULL,
  `contact_details` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Departments` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(45) NULL DEFAULT NULL,
  `BookStock_book_stock_id` INT NOT NULL,
  PRIMARY KEY (`department_id`),
  INDEX `fk_Departments_BookStore1_idx` (`BookStock_book_stock_id` ASC) VISIBLE,
  CONSTRAINT `fk_Departments_BookStore1`
    FOREIGN KEY (`BookStock_book_stock_id`)
    REFERENCES `OnlineBookstoreSystem`.`BookStock` (`book_stock_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Orders` (
  `orders_id` INT NOT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `order_date` DATE NULL DEFAULT NULL,
  `order_status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`orders_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `OnlineBookstoreSystem`.`Customers` (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Discounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Discounts` (
  `discount_id` INT NOT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `percentage` DECIMAL(5,2) NULL DEFAULT NULL,
  `expiry_date` DATE NULL DEFAULT NULL,
  `Orders_orders_id` INT NOT NULL,
  PRIMARY KEY (`discount_id`),
  INDEX `fk_Discounts_Orders1_idx` (`Orders_orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_Discounts_Orders1`
    FOREIGN KEY (`Orders_orders_id`)
    REFERENCES `OnlineBookstoreSystem`.`Orders` (`orders_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Employees` (
  `employee_id` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL DEFAULT NULL,
  `contact_details` VARCHAR(100) NULL DEFAULT NULL,
  `Departments_department_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_Employees_Departments1_idx` (`Departments_department_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employees_Departments1`
    FOREIGN KEY (`Departments_department_id`)
    REFERENCES `OnlineBookstoreSystem`.`Departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Order_Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Order_Items` (
  `item_id` INT NOT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `book_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `OnlineBookstoreSystem`.`Books` (`book_id`),
  CONSTRAINT `order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `OnlineBookstoreSystem`.`Orders` (`orders_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Payments` (
  `payment_id` INT NOT NULL,
  `customer_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  `payment_amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `payment_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`payment_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `order_id_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `payment_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `OnlineBookstoreSystem`.`Customers` (`customer_id`),
  CONSTRAINT `payment_order_id`
    FOREIGN KEY (`order_id`)
    REFERENCES `OnlineBookstoreSystem`.`Orders` (`orders_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `OnlineBookstoreSystem`.`Reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstoreSystem`.`Reviews` (
  `review_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `rating` INT NULL DEFAULT NULL,
  `comments` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`review_id`),
  INDEX `book_id_idx` (`book_id` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `review_book_id`
    FOREIGN KEY (`book_id`)
    REFERENCES `OnlineBookstoreSystem`.`Books` (`book_id`),
  CONSTRAINT `review_customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `OnlineBookstoreSystem`.`Customers` (`customer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
